# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'


target 'rule_apple_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rule_apple_demo
pod 'Moya', '~> 15.0'
pod 'StepperView','~> 1.6.7'
pod 'FloatingLabelTextFieldSwiftUI'
  target 'rule_apple_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rule_apple_demoUITests' do
    # Pods for testing
  end

end
